services:
  notepad:
    image: hgnguyen37/simple-clipboard
    container_name: my_single_note
    ports:
      - "8099:80"
    volumes:
      - ./data-test.txt:/var/www/html/data.txt   # Mount personal txt file
    restart: always